version: '3.8'

services:
  # PHP приложение Laravel (API)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dockerized-laravel-app
    restart: unless-stopped
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dockerized-laravel-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # Next.js Frontend (SSR)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dockerized-laravel-frontend
    restart: unless-stopped
    environment:
      - INTERNAL_API_URL=http://webserver:8080/api
      - NODE_OPTIONS=--dns-result-order=ipv4first
    networks:
      - dockerized-laravel-network
    depends_on:
      - app

  # Веб-сервер Nginx
  webserver:
    image: nginx:alpine
    container_name: dockerized-laravel-webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dockerized-laravel-network
    depends_on:
      - app
      - frontend

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: dockerized-laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    volumes:
      - dockerized-laravel-data:/var/lib/mysql
    networks:
      - dockerized-laravel-network
    ports:
      - "3307:3306"

# Сети Docker
networks:
  dockerized-laravel-network:
    driver: bridge

# Постоянные файлы
volumes:
  dockerized-laravel-data:
    driver: local
